# Generated by Django 6.0.2 on 2026-06-18 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('visibilidad', models.CharField(choices=[('PUBLICO', 'Público'), ('ANONIMO', 'Anónimo')], default='PUBLICO', max_length=20)),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('aceptada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'conversacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardado',
            fields=[
                ('id_guardado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'guardado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('visibilidad', models.CharField(choices=[('PUBLICO', 'Público'), ('ANONIMO', 'Anónimo')], default='PUBLICO', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id_reaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reaccion', models.CharField(choices=[('TE_ENTIENDO', 'Te entiendo'), ('ME_PASO_IGUAL', 'Me pasó igual'), ('SIGUE_ADELANTE', 'Sigue adelante'), ('TENGO_UN_CONSEJO', 'Tengo un consejo')], max_length=50)),
                ('fecha_reaccion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
